// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.5
// source: common-identity.proto

package common_identity

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StGeneratorIDCode32Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StGeneratorIDCode32Req) Reset() {
	*x = StGeneratorIDCode32Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_identity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StGeneratorIDCode32Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StGeneratorIDCode32Req) ProtoMessage() {}

func (x *StGeneratorIDCode32Req) ProtoReflect() protoreflect.Message {
	mi := &file_common_identity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StGeneratorIDCode32Req.ProtoReflect.Descriptor instead.
func (*StGeneratorIDCode32Req) Descriptor() ([]byte, []int) {
	return file_common_identity_proto_rawDescGZIP(), []int{0}
}

type StGeneratorIDCode32Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdCode32 string `protobuf:"bytes,1,opt,name=idCode32,proto3" json:"idCode32,omitempty"`
}

func (x *StGeneratorIDCode32Rsp) Reset() {
	*x = StGeneratorIDCode32Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_identity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StGeneratorIDCode32Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StGeneratorIDCode32Rsp) ProtoMessage() {}

func (x *StGeneratorIDCode32Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_common_identity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StGeneratorIDCode32Rsp.ProtoReflect.Descriptor instead.
func (*StGeneratorIDCode32Rsp) Descriptor() ([]byte, []int) {
	return file_common_identity_proto_rawDescGZIP(), []int{1}
}

func (x *StGeneratorIDCode32Rsp) GetIdCode32() string {
	if x != nil {
		return x.IdCode32
	}
	return ""
}

type StGeneratorIDCode16Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StGeneratorIDCode16Req) Reset() {
	*x = StGeneratorIDCode16Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_identity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StGeneratorIDCode16Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StGeneratorIDCode16Req) ProtoMessage() {}

func (x *StGeneratorIDCode16Req) ProtoReflect() protoreflect.Message {
	mi := &file_common_identity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StGeneratorIDCode16Req.ProtoReflect.Descriptor instead.
func (*StGeneratorIDCode16Req) Descriptor() ([]byte, []int) {
	return file_common_identity_proto_rawDescGZIP(), []int{2}
}

type StGeneratorIDCode16Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdCode16 string `protobuf:"bytes,1,opt,name=idCode16,proto3" json:"idCode16,omitempty"`
}

func (x *StGeneratorIDCode16Rsp) Reset() {
	*x = StGeneratorIDCode16Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_identity_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StGeneratorIDCode16Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StGeneratorIDCode16Rsp) ProtoMessage() {}

func (x *StGeneratorIDCode16Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_common_identity_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StGeneratorIDCode16Rsp.ProtoReflect.Descriptor instead.
func (*StGeneratorIDCode16Rsp) Descriptor() ([]byte, []int) {
	return file_common_identity_proto_rawDescGZIP(), []int{3}
}

func (x *StGeneratorIDCode16Rsp) GetIdCode16() string {
	if x != nil {
		return x.IdCode16
	}
	return ""
}

var File_common_identity_proto protoreflect.FileDescriptor

var file_common_identity_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2d, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x73, 0x74, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x43, 0x6f, 0x64, 0x65, 0x33, 0x32, 0x52,
	0x65, 0x71, 0x22, 0x34, 0x0a, 0x16, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x49, 0x44, 0x43, 0x6f, 0x64, 0x65, 0x33, 0x32, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x33, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x33, 0x32, 0x22, 0x18, 0x0a, 0x16, 0x73, 0x74, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x43, 0x6f, 0x64, 0x65, 0x31, 0x36, 0x52,
	0x65, 0x71, 0x22, 0x34, 0x0a, 0x16, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x49, 0x44, 0x43, 0x6f, 0x64, 0x65, 0x31, 0x36, 0x52, 0x73, 0x70, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x31, 0x36, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x31, 0x36, 0x32, 0xe9, 0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x6a, 0x0a, 0x14,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x43, 0x6f, 0x64, 0x65, 0x31,
	0x36, 0x52, 0x65, 0x71, 0x12, 0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x49, 0x44, 0x43, 0x6f, 0x64, 0x65, 0x31, 0x36, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x73, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x43, 0x6f, 0x64,
	0x65, 0x31, 0x36, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x6a, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x43, 0x6f, 0x64, 0x65, 0x33, 0x32, 0x52, 0x65, 0x71,
	0x12, 0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2e, 0x73, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x44,
	0x43, 0x6f, 0x64, 0x65, 0x33, 0x32, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x73, 0x74, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x43, 0x6f, 0x64, 0x65, 0x33, 0x32, 0x52,
	0x73, 0x70, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_identity_proto_rawDescOnce sync.Once
	file_common_identity_proto_rawDescData = file_common_identity_proto_rawDesc
)

func file_common_identity_proto_rawDescGZIP() []byte {
	file_common_identity_proto_rawDescOnce.Do(func() {
		file_common_identity_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_identity_proto_rawDescData)
	})
	return file_common_identity_proto_rawDescData
}

var file_common_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_identity_proto_goTypes = []interface{}{
	(*StGeneratorIDCode32Req)(nil), // 0: common_identity.stGeneratorIDCode32Req
	(*StGeneratorIDCode32Rsp)(nil), // 1: common_identity.stGeneratorIDCode32Rsp
	(*StGeneratorIDCode16Req)(nil), // 2: common_identity.stGeneratorIDCode16Req
	(*StGeneratorIDCode16Rsp)(nil), // 3: common_identity.stGeneratorIDCode16Rsp
}
var file_common_identity_proto_depIdxs = []int32{
	2, // 0: common_identity.common_identity.GeneratorIDCode16Req:input_type -> common_identity.stGeneratorIDCode16Req
	0, // 1: common_identity.common_identity.GeneratorIDCode32Req:input_type -> common_identity.stGeneratorIDCode32Req
	3, // 2: common_identity.common_identity.GeneratorIDCode16Req:output_type -> common_identity.stGeneratorIDCode16Rsp
	1, // 3: common_identity.common_identity.GeneratorIDCode32Req:output_type -> common_identity.stGeneratorIDCode32Rsp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_identity_proto_init() }
func file_common_identity_proto_init() {
	if File_common_identity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_identity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StGeneratorIDCode32Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_identity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StGeneratorIDCode32Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_identity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StGeneratorIDCode16Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_identity_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StGeneratorIDCode16Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_identity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_identity_proto_goTypes,
		DependencyIndexes: file_common_identity_proto_depIdxs,
		MessageInfos:      file_common_identity_proto_msgTypes,
	}.Build()
	File_common_identity_proto = out.File
	file_common_identity_proto_rawDesc = nil
	file_common_identity_proto_goTypes = nil
	file_common_identity_proto_depIdxs = nil
}
